### ISSUE TITLE
JSON preview doesn't work

### ISSUE THREAD

**Issue by monoflash** [getinsomnia/insomnia.rest#10]
Insomnia version Версия 5.7.0 (5.7.0.911)

![JSON preview doesn't work](https://www.dropbox.com/s/wqxypkswl6csexr/insomnia%20%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F%205.7.0%20%285.7.0.911%29.png?raw=1)

**Comment by gschier** [comment]
This is a duplicate of https://github.com/getinsomnia/insomnia/issues/395
