### ISSUE TITLE
Why does Insomnia site use Development version of React ?

### ISSUE THREAD

**Issue by karuppiah7890** [getinsomnia/insomnia.rest#11]
![react](https://user-images.githubusercontent.com/12808424/29066827-10556d9c-7c4e-11e7-8335-07e5ef47edc3.png)

**Comment by gschier** [comment]
It was like that because I had some UglifyJS errors I couldn't figure out. Gave it another try and got it working, though. Thanks for reminding me that it needed to be done! 😄

**Comment by gschier** [comment]
P.S. I also changed it to the ReactJS is only included on pages it's used `/app/*`.

**Comment by karuppiah7890** [comment]
:) It's just that I am seeing a lot of sites using Development version of React here and there, so I got curious
