### ISSUE TITLE
https://insomnia.rest/download/ lacks AppImage download

### ISSUE THREAD

**Issue by probonopd** [getinsomnia/insomnia.rest#15]
https://insomnia.rest/documentation/installation/#linux describes AppImage, but it is entirely unclear where to download the AppImage from.

https://insomnia.rest/download/ lacks an AppImage download. Also, please provide the AppImage for download on GitHub Releases, thanks.

Reference:
AppImage/AppImageHub#15

**Comment by gschier** [comment]
Oops, sorry @probonopd. I updated the download page and accidentally removed the link. Adding it to the `documentation/installation` page now.

There are already `AppImage` packages in the releases.

**Comment by probonopd** [comment]
Thanks 👍

**Comment by gschier** [comment]
I just reverted it for now. Might spend some more time on this later.
