### ISSUE TITLE
insomnia.desktop does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [getinsomnia/insomnia.rest#16]
`insomnia.desktop: error: value "Development" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character`

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266143242#L542

**Comment by probonopd** [comment]
Unfortunately this is still true in insomnia-5.8.4-x86_64.AppImage. Updating electron-builder should solve it.

**Comment by gschier** [comment]
Hi @probonopd,

I haven't had time to look at this yet but I am hesitant to update `electron-builder` since it regularly introduces breaking changes. Are you aware of what version of `electron-builder` fixed this?

**Comment by probonopd** [comment]
I think this one:
https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1
> linux: compute app category by mac category (022d542)

**Comment by gschier** [comment]
@probonopd currently finishing up a PR to upgrade Electron Builder to latest. Can you tell me how to extract a `.AppImage` file on Mac so I can check to see if the `insomnia.desktop` is now correct?

**Comment by gschier** [comment]
Also, I realized I could have probably just added a semicolon here to fix it

https://github.com/getinsomnia/insomnia/blob/b3754a07e3f6976d05dc991a73786740b1ed1a38/package.json#L105

**Comment by probonopd** [comment]
An AppImage is a Linux ELF binary with a squashfs filesystem image appended. 

To extract it on macOS, you need to know the offset at which the squashfs image begins. I have written [code](https://github.com/AppImage/AppImageKit/blob/appimagetool/master/elf.h) for this for Linux, I have never tried to compile this for macOS. On Linux, you can run

```
./Some.AppImage --appimage-offset
xxxxx <-- this is the offset at which the squashfs image begins
```

On macOS, if you have homebrew installed, you shoud be able to install `brew install squashfs`, and then run `unsquashfs`.

Knowing the offset, you could use `dd` on the Mac to transfer the squashfs image into its own file, and run `unsquashfs` on it (squashfs-tools trunk even has a command line switch that lets you extract a squashfs image from a given offset so you don't need `dd` anymore, but I don't know if that can be compiled on macOS already).
