### ISSUE TITLE
Homepage button text is not centered 📄

### ISSUE THREAD

**Issue by whmountains** [getinsomnia/insomnia.rest#17]
![screen shot 2017-08-23 at 7 00 26 pm](https://user-images.githubusercontent.com/8680147/29640439-003c2302-882d-11e7-8f78-e4679963c4a1.png)

**Comment by gschier** [comment]
What are you viewing this on? It's centered on all the browsers I'm using.

**Comment by whmountains** [comment]
Firefox Nightly :woman_shrugging:

**Comment by gschier** [comment]
On what OS?

**Comment by whmountains** [comment]
MacOS High Sierra Beta.

I realize that you may not care if the text is centered on such a niche platform.  That's fine with me, but you might as well know about it.

**Comment by whmountains** [comment]
I went ahead and tested on Firefox Stable and saw the same issue.  Maybe this isn't so niche after all :)

**Comment by gschier** [comment]
Weird, I can't reproduce it on FireFox on Mac either. I feel like it's probably due to us having a different set of OS fonts available.

**Comment by whmountains** [comment]
That makes sense.  Some manual centering with flexbox or display: table-cell should do the trick :)
