### ISSUE TITLE
Headers get truncated on ':' character

### ISSUE THREAD

**Issue by eztinkerdreams** [getinsomnia/insomnia.rest#6]
On the Headers tab for the response view, if the head value contains a `:` character, the header gets truncated.

**Comment by gschier** [comment]
What app version are you using @eztinkerdreams. I remember fixing this a long time ago and can't seem to reproduce it on v5.2.0.

**Comment by gschier** [comment]
Ohh, nvm. I fixed it for the Request Headers tab, not **Response** headers. Got it.

**Comment by gschier** [comment]
Just noticed that this issue is on the wrong repository. I've moved it to https://github.com/getinsomnia/insomnia/issues/293
